export const ConstantsProjects = [
  {
    title:"E-commerce",
    link:"https://ecommerce-eta-coral.vercel.app/",
    description:"Uma estrutura de loja virtual simples com amostra de produtos e sistema de carrinho inteligente",
    technologies:"next-js| sanity | context-api",
    date:"13/10/2022",
    repository:"https://github.com/MatheusCardosoc0/ecommerce",
    image:'/e-commerce-2.png',
  },
  {
    title:"Liricks",
    link:"https://stunning-faun-bd5d93.netlify.app/",
    description:"Uma aplicação para tocar, pesquisar e ver letra das musicas capturando os dados da Shazam api da RapidApi",
    technologies:"react-js | tailwindcss | Rapid-api | redux-tolkit",
    date:"31/10/2022",
    repository:"https://github.com/MatheusCardosoc0/SpotifyClone",
    image:'/Lyricks.png',
  },
  {
    title:"Twitter reimaginado",
    link:"https://twitter-clone-omega-drab.vercel.app/",
    description:"Uma reimaginação da interface do twitter, usando sanity.io como banco de dados",
    technologies:"next-js | tailwindcss | typescript | next-auth com o twitter | sanity.io",
    date:"01/12/2022",
    repository:"https://github.com/MatheusCardosoc0/TwitterClone",
    image:'/twitter.png',
  },
  {
    title:"Jogo de combate rpg por turno",
    link:"https://coruscating-treacle-47a916.netlify.app/",
    description:"Um jogo que permite a escolha de personagens para se confrontarem em um combate por turnos.",
    technologies:"react-js | tailwindcss | typescript | context-api",
    date:"29/10/2022",
    repository:"https://github.com/MatheusCardosoc0/CombaTurn",
    image:'/RpgGame.png',
  },
  {
    title:"Jogo de combate rpg por turno",
    link:"https://tubular-biscotti-da756e.netlify.app/",
    description:"Uma aplicação que pega dados da country-api, realiza pesquisas por nome e filtragem por região, área e população",
    technologies:"react-js | tailwindcss | typescript | Country-api",
    date:"04/11/2022",
    repository:"https://github.com/MatheusCardosoc0/GaleryCountries",
    image:'/CountryGalery.png',
  },
]